# Generated by Django 4.1.7 on 2023-03-15 23:58

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "last_login",
                    models.CharField(
                        default=datetime.datetime(2023, 3, 15, 23, 58, 18, 153973),
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "admin"), ("user", "user")],
                        default="user",
                        max_length=7,
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
